package com.community.tools.service.openai;

import org.springframework.ai.chat.ChatClient;
import org.springframework.stereotype.Service;

@Service
public class OpenAiService {

  private final ChatClient chatClient;

  public OpenAiService(ChatClient chatClient) {
    this.chatClient = chatClient;
  }

  /**
   * Processes the user's request by sending a prompt to the OpenAI API through the ChatClient.
   *
   * @param prompt The user's request to be sent to the OpenAI API.
   * @return A string response generated by the AI, ready for use.
   *
   * @see ChatClient#call(String) The underlying method responsible for making the API call.
   */
  public String processPrompt(String prompt) {
    return chatClient.call(prompt);
  }
}
